# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_potentialclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
