# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20180612_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialclient',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
