# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_auto_20180402_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField()),
                ('processes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastChanged', models.DateTimeField(auto_now=True)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
