# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-28 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
