# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180428_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coc',
            field=models.FileField(blank=True, null=True, upload_to='media/coc'),
        ),
    ]
