# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coc',
        ),
    ]
