# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_floor', '0003_auto_20180428_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='done_processes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
