# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_floor', '0004_product_done_processes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='processes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
