# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-19 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_floor', '0005_auto_20180430_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parameters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
