# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_floor', '0008_auto_20180523_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coc',
            field=models.FileField(blank=True, null=True, upload_to='media/coc'),
        ),
    ]
