# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_floor', '0011_auto_20180529_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='routing',
            field=models.FileField(blank=True, null=True, upload_to='media/routing'),
        ),
    ]
